version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/practic2
      - SPRING_DATASOURCE_USERNAME=root1
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:15.4-bullseye'
    container_name: db
    environment:
      - POSTGRES_DB=practic2
      - POSTGRES_USER=root1
      - POSTGRES_PASSWORD=123